import { type ClassValue, clsx } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

// Mock data for the MVP
export const mockUsers = [
  {
    id: "1",
    full_name: "John Doe",
    email: "john@example.com",
    bio: "Full-stack developer with 5 years of experience",
    industry: ["Software Development", "Web Development"],
    skills: ["React", "Node.js", "TypeScript", "MongoDB"],
    linkedin_url: "https://linkedin.com/in/johndoe",
    website_url: "https://johndoe.dev",
    resume_url: "/resume/johndoe.pdf",
    additional_links: [{ title: "GitHub", url: "https://github.com/johndoe" }],
    contact: { email: "john@example.com", phone: "123-456-7890" },
    views: 120,
    graduation_year: 2022,
    is_texas_am_affiliate: true,
    avatar: "/placeholder.svg?height=100&width=100",
  },
  {
    id: "2",
    full_name: "Jane Smith",
    email: "jane@example.com",
    bio: "UX/UI designer specializing in user research and interface design",
    industry: ["Design", "User Experience"],
    skills: ["Figma", "Adobe XD", "User Research", "Prototyping"],
    linkedin_url: "https://linkedin.com/in/janesmith",
    website_url: "https://janesmith.design",
    resume_url: "/resume/janesmith.pdf",
    additional_links: [{ title: "Dribbble", url: "https://dribbble.com/janesmith" }],
    contact: { email: "jane@example.com", phone: "234-567-8901" },
    views: 85,
    graduation_year: 2023,
    is_texas_am_affiliate: true,
    avatar: "/placeholder.svg?height=100&width=100",
  },
  {
    id: "3",
    full_name: "Robert Johnson",
    email: "robert@example.com",
    bio: "Entrepreneur with experience in launching tech startups",
    industry: ["Entrepreneurship", "Business Development"],
    skills: ["Business Strategy", "Fundraising", "Marketing", "Team Building"],
    linkedin_url: "https://linkedin.com/in/robertjohnson",
    website_url: "https://robertjohnson.co",
    resume_url: "/resume/robertjohnson.pdf",
    additional_links: [{ title: "AngelList", url: "https://angel.co/robertjohnson" }],
    contact: { email: "robert@example.com", phone: "345-678-9012" },
    views: 150,
    graduation_year: 2020,
    is_texas_am_affiliate: false,
    avatar: "/placeholder.svg?height=100&width=100",
  },
  {
    id: "4",
    full_name: "Emily Chen",
    email: "emily@example.com",
    bio: "Data scientist with expertise in machine learning and AI",
    industry: ["Data Science", "Artificial Intelligence"],
    skills: ["Python", "TensorFlow", "Data Analysis", "Machine Learning"],
    linkedin_url: "https://linkedin.com/in/emilychen",
    website_url: "https://emilychen.io",
    resume_url: "/resume/emilychen.pdf",
    additional_links: [{ title: "Kaggle", url: "https://kaggle.com/emilychen" }],
    contact: { email: "emily@example.com", phone: "456-789-0123" },
    views: 95,
    graduation_year: 2021,
    is_texas_am_affiliate: false,
    avatar: "/placeholder.svg?height=100&width=100",
  },
  {
    id: "5",
    full_name: "Michael Brown",
    email: "michael@example.com",
    bio: "Product manager with a background in software engineering",
    industry: ["Product Management", "Software Development"],
    skills: ["Product Strategy", "Agile", "User Stories", "Roadmapping"],
    linkedin_url: "https://linkedin.com/in/michaelbrown",
    website_url: "https://michaelbrown.me",
    resume_url: "/resume/michaelbrown.pdf",
    additional_links: [{ title: "Medium", url: "https://medium.com/@michaelbrown" }],
    contact: { email: "michael@example.com", phone: "567-890-1234" },
    views: 110,
    graduation_year: 2019,
    is_texas_am_affiliate: true,
    avatar: "/placeholder.svg?height=100&width=100",
  },
]

export const mockProjects = [
  {
    id: "1",
    title: "AI-Powered Learning Platform",
    description:
      "Building an adaptive learning platform that uses AI to personalize educational content for students based on their learning style and progress.",
    owner_id: "1",
    is_idea: false,
    recruitment_status: "Recruiting team members",
    industry: ["Education", "Artificial Intelligence"],
    required_skills: ["Machine Learning", "React", "Node.js", "Python"],
    location_type: "Remote",
    estimated_start: "2025-03-15",
    estimated_end: "2025-09-15",
    contact_info: { email: "john@example.com", phone: "123-456-7890" },
    views: 250,
    created_at: "2025-02-10T12:00:00Z",
    last_updated: "2025-02-20T15:30:00Z",
    project_status: "Not Started",
    deleted: false,
  },
  {
    id: "2",
    title: "Sustainable Fashion Marketplace",
    description:
      "Creating a marketplace that connects eco-conscious consumers with sustainable fashion brands and second-hand clothing sellers.",
    owner_id: "2",
    is_idea: true,
    recruitment_status: "Looking for co-founders",
    industry: ["Fashion", "E-commerce", "Sustainability"],
    required_skills: ["UI/UX Design", "React", "Node.js", "Marketing"],
    location_type: "Hybrid",
    estimated_start: "2025-04-01",
    estimated_end: "2025-10-31",
    contact_info: { email: "jane@example.com", phone: "234-567-8901" },
    views: 180,
    created_at: "2025-02-15T09:45:00Z",
    last_updated: "2025-02-22T11:20:00Z",
    project_status: "Idea Phase",
    deleted: false,
  },
  {
    id: "3",
    title: "Smart Home Energy Management System",
    description:
      "Developing a system that optimizes energy usage in homes by learning from user behavior and integrating with smart home devices.",
    owner_id: "3",
    is_idea: false,
    recruitment_status: "Full team, seeking investment",
    industry: ["IoT", "Energy", "Smart Home"],
    required_skills: ["IoT Development", "Machine Learning", "Mobile Development", "Hardware Design"],
    location_type: "In-person",
    estimated_start: "2025-03-01",
    estimated_end: "2026-03-01",
    contact_info: { email: "robert@example.com", phone: "345-678-9012" },
    views: 320,
    created_at: "2025-02-05T14:30:00Z",
    last_updated: "2025-02-25T16:45:00Z",
    project_status: "Ongoing",
    deleted: false,
  },
  {
    id: "4",
    title: "Community-Based Mental Health App",
    description:
      "Creating a mobile application that connects individuals with mental health resources and community support groups in their area.",
    owner_id: "4",
    is_idea: false,
    recruitment_status: "Recruiting team members",
    industry: ["Healthcare", "Mental Health", "Mobile Apps"],
    required_skills: ["React Native", "Firebase", "UI/UX Design", "Healthcare Knowledge"],
    location_type: "Remote",
    estimated_start: "2025-04-15",
    estimated_end: "2025-10-15",
    contact_info: { email: "emily@example.com", phone: "456-789-0123" },
    views: 210,
    created_at: "2025-02-18T10:15:00Z",
    last_updated: "2025-02-24T13:40:00Z",
    project_status: "Not Started",
    deleted: false,
  },
  {
    id: "5",
    title: "Blockchain-Based Supply Chain Tracking",
    description:
      "Building a platform that uses blockchain technology to track products through the supply chain, ensuring transparency and authenticity.",
    owner_id: "5",
    is_idea: true,
    recruitment_status: "Looking for technical co-founder",
    industry: ["Blockchain", "Supply Chain", "Logistics"],
    required_skills: ["Blockchain Development", "Smart Contracts", "Full-stack Development", "Supply Chain Knowledge"],
    location_type: "Hybrid",
    estimated_start: "2025-05-01",
    estimated_end: "2026-05-01",
    contact_info: { email: "michael@example.com", phone: "567-890-1234" },
    views: 150,
    created_at: "2025-02-20T08:30:00Z",
    last_updated: "2025-02-26T09:15:00Z",
    project_status: "Idea Phase",
    deleted: false,
  },
  {
    id: "6",
    title: "AR Campus Tour Guide",
    description:
      "Developing an augmented reality application that provides interactive tours of the Texas A&M campus for prospective students and visitors.",
    owner_id: "1",
    is_idea: false,
    recruitment_status: "Recruiting team members",
    industry: ["Augmented Reality", "Education", "Mobile Apps"],
    required_skills: ["AR Development", "Unity", "3D Modeling", "Mobile Development"],
    location_type: "In-person",
    estimated_start: "2025-03-20",
    estimated_end: "2025-08-20",
    contact_info: { email: "john@example.com", phone: "123-456-7890" },
    views: 175,
    created_at: "2025-02-12T11:20:00Z",
    last_updated: "2025-02-23T14:10:00Z",
    project_status: "Not Started",
    deleted: false,
  },
]

export const mockUserBookmarks = [
  { id: "1", user_id: "1", bookmarked_user_id: "2", saved_at: "2025-02-15T10:30:00Z" },
  { id: "2", user_id: "1", bookmarked_user_id: "3", saved_at: "2025-02-18T14:45:00Z" },
  { id: "3", user_id: "2", bookmarked_user_id: "1", saved_at: "2025-02-20T09:15:00Z" },
]

export const mockProjectBookmarks = [
  { id: "1", user_id: "1", project_id: "3", saved_at: "2025-02-16T11:20:00Z" },
  { id: "2", user_id: "1", project_id: "4", saved_at: "2025-02-19T15:30:00Z" },
  { id: "3", user_id: "2", project_id: "1", saved_at: "2025-02-21T10:45:00Z" },
  { id: "4", user_id: "3", project_id: "2", saved_at: "2025-02-22T13:10:00Z" },
]

// Helper function to format date
export function formatDate(dateString: string) {
  return new Date(dateString).toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  })
}

